# Generated by Django 3.0 on 2019-12-06 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('video_url', models.URLField()),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenuvideo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContenuText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('contenu', models.TextField(verbose_name='Description du contenu')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenutext_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.PositiveIntegerField()),
                ('content_types', models.ForeignKey(limit_choices_to={'model__in': ('ContenuText', 'ContenuFichier', 'ContenuImage', 'ContenuVideo')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Modules')),
            ],
        ),
        migrations.CreateModel(
            name='ContenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('image', models.FileField(upload_to='images', verbose_name='Ajouter une image')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenuimage_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContenuFichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('fichier', models.FileField(upload_to='fichier', verbose_name='Ajouter un fichier')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenufichier_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
