# Generated by Django 3.0 on 2019-12-06 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0003_auto_20191206_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='etudiants',
            field=models.ManyToManyField(blank=True, related_name='rejoindre_cours', to=settings.AUTH_USER_MODEL),
        ),
    ]
