# Generated by Django 3.0 on 2019-12-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_cours_etudiants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenus',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='cours.Modules'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cours.Cours'),
        ),
    ]
