# Generated by Django 3.0 on 2019-12-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_auto_20191207_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenuimage',
            old_name='image',
            new_name='fichier',
        ),
    ]
