# Generated by Django 3.0 on 2019-12-07 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0008_auto_20191207_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('fichier', models.FileField(upload_to='fichier', verbose_name='Ajouter un fichier')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichier_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('fichier', models.FileField(upload_to='images', verbose_name='Ajouter une image')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('contenu', models.TextField(verbose_name='Description du contenu')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('video_url', models.URLField(verbose_name="Ajouter l'url de la video")),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contenuimage',
            name='instructeur',
        ),
        migrations.RemoveField(
            model_name='contenutext',
            name='instructeur',
        ),
        migrations.RemoveField(
            model_name='contenuvideo',
            name='instructeur',
        ),
        migrations.DeleteModel(
            name='ContenuFichier',
        ),
        migrations.DeleteModel(
            name='ContenuImage',
        ),
        migrations.DeleteModel(
            name='ContenuText',
        ),
        migrations.DeleteModel(
            name='ContenuVideo',
        ),
    ]
