# Generated by Django 3.0 on 2019-12-07 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0009_auto_20191207_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du contenu')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise en ligne')),
                ('file', models.FileField(upload_to='fichier', verbose_name='Ajouter un fichier')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='image',
            old_name='fichier',
            new_name='file',
        ),
        migrations.DeleteModel(
            name='Fichier',
        ),
    ]
