# Generated by Django 3.0 on 2019-12-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cours', '0010_auto_20191207_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenus',
            options={'ordering': ['ordre']},
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-date_de_creation']},
        ),
        migrations.AlterModelOptions(
            name='matieres',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ['ordre']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='contenus',
            name='content_types',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise en ligne'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise en ligne'),
        ),
        migrations.AlterField(
            model_name='text',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise en ligne'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise en ligne'),
        ),
    ]
